name: Pull Request
on:
  - pull_request
  - push

jobs:
  test:
    runs_on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

      steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
            cache: poetry

        - name: Install
          run: poetry install --only test,man

  mypy:
    runs_on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

      steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
            cache: poetry

        - name: Install
          run: poetry install --only mypy,man

        - name: Pytest
          run: poetry run pytest