name: Release Request
on:
  release:
    types: ["published"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Set Project Version
        shell: bash
        run: |
          version_ref="${{github.ref}}"
          poetry version "${version_ref#refs/tags/}"

      - name: Build
        run: poetry build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/


  attach-to-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish to GitHub release page
        uses: svenstaro/upload-release-action@v2
        if: inputs.publish-to-github == 'true' && github.event_name == 'release'
        with:
          file: "dist/*"
          file_glob: true
          tag: ${{ github.ref }}
